spring:
  data:
    mongodb:
      uri: mongodb+srv://theekshanagamage056_db_user:f8sHpCHrOJXYvFKb@cluster0.aveyph5.mongodb.net/tsldb?retryWrites=true&w=majority&appName=Cluster0

logging:
  level:
    com.tsl: DEBUG
    org.springframework.web: INFO
    org.springframework.data.mongodb: INFO